name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Python tests
        uses: minakoari/actions-test@master
        with:
          args: if [ -f requirements.txt ]; then pip install -r requirements.txt; fi && pytest
